openapi: 3.0.3
info:
  title: 'TODO test app API Documentation'
  description: 'Completed test task: "Developing a simple API for task management."'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/tasks:
    get:
      summary: ''
      operationId: getApiTasks
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      title: 'New task'
                      description: 'Eius et animi quos velit et.'
                      status: todo
                      created_at: '2025-11-04T06:17:04.000000Z'
                      updated_at: '2025-11-04T06:17:04.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'New task'
                        description: 'Eius et animi quos velit et.'
                        status: todo
                        created_at: '2025-11-04T06:17:04.000000Z'
                        updated_at: '2025-11-04T06:17:04.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'New task'
                        description:
                          type: string
                          example: 'Eius et animi quos velit et.'
                        status:
                          type: string
                          example: todo
                        created_at:
                          type: string
                          example: '2025-11-04T06:17:04.000000Z'
                        updated_at:
                          type: string
                          example: '2025-11-04T06:17:04.000000Z'
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiTasks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: 'New Task'
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'New description'
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: pending
                  nullable: false
      security: []
  '/api/tasks/{id}':
    get:
      summary: ''
      operationId: getApiTasksId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    title: 'New task'
                    description: 'Eius et animi quos velit et.'
                    status: todo
                    created_at: '2025-11-04T06:17:04.000000Z'
                    updated_at: '2025-11-04T06:17:04.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'New task'
                      description:
                        type: string
                        example: 'Eius et animi quos velit et.'
                      status:
                        type: string
                        example: todo
                      created_at:
                        type: string
                        example: '2025-11-04T06:17:04.000000Z'
                      updated_at:
                        type: string
                        example: '2025-11-04T06:17:04.000000Z'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: b
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Updated description'
                  nullable: true
                status:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: v
                  nullable: false
      security: []
    delete:
      summary: ''
      operationId: deleteApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
